import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';


export default function Home() {

  const productsApiUrl = process.env.NEXT_PUBLIC_BACKEND_PRODUCTS ;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
<h1>HomePage</h1>
 <Link href={'./Entities/Products'}>Products</Link>
      </main>
    </>
  )
}
